#!/usr/bin/env bash
# display the time
hour=0
min=1

while (( hour<=12 ))
do
    echo "$min"
    : $(( min++ ))
    if (( min>59 ))
    then
    if (( hour<12 ))
    then
        : $(( hour++ ))
	    min=1
		else
		    : $(( hour++ ))
		    fi
    fi
done